### ISSUE TITLE
Comments on Custom post types dont work

### ISSUE THREAD

**Issue by dpacmittal** [WordPoints/wordpoints#491] opened 2016-08-31 17:04 UTC
Comments on custom post types are not triggering point addition. Not sure why or how? I don't even have many plugins enabled. No errors in the log.

**Comment by JDGrimes** [comment] 2016-08-31 19:04
@dpacmittal Could you tell me which plugins you are using, specifically? Also, are you using the reactions on the Points Types screen to award points, or are you using the legacy hooks on the Points Hooks screen (only shown on legacy sites)?

**Comment by JDGrimes** [comment] 2016-09-30 19:52
Hey @dpacmittal, I've been trying to reproduce this, but I haven't been able to.

I thought perhaps this is being caused by the plugins providing the custom post types registering those post types later than WordPoints is registering the events. But then the events wouldn't be displayed at all. So I guess that isn't it.

I can't really investigate this further without a specific example of a custom post type that this isn't working for. If you can reply and give me an example of a plugin you are using that adds a custom post type, but WordPoints doesn't award points for it, that would be helpful.

**Comment by JDGrimes** [comment] 2016-11-18 13:47
I still haven't been able to reproduce this, and I haven't received any other reports of this issue, so I'm going to close this. Feel free to reopen with more information if you are still experiencing problems.

**Comment by JDGrimes** [comment] 2017-01-13 21:31
I've just received [another report](https://wordpress.org/support/topic/no-points-logged-for-bbpress-or-geodirectory-events/#post-8652878) of events for custom post types not working, although this time it was actually publish post events for bbPress and Geodirectory. But I was able to reproduce with bbPress, and discovered that although the router was being triggered correctly by the action, the actions weren't registered with the router—though the events were. Just the actions for the core post types were registered. So my suspicion that this was relating to the registration order turned out to be correct, since bbPress doesn't register it's post types until `init` `0`, whereas we initialize the actions on `plugins_loaded`. To fix this, we either need to initialize the actions API later, or register the post type events retroactively.

**Comment by JDGrimes** [comment] 2017-01-13 22:06
I think the best thing to do is register the actions retroactively, since that way we can continue to fire as early as we do. That avoids the potential back-compat issues with moving the initialization of the hooks API to be later.

**Comment by JDGrimes** [comment] 2017-01-13 22:17
It is as simple as hooking the post type action/event/entity registration functions to the `registered_post_type` action. However, if we do that right in `filters.php`, the core post types, and any others that are registered before the hooks API is initialized, will end up having their stuff registered twice. However, this is not a serious problem, because they won't actually be registered twice, the second time will just overwrite whatever was registered previously.

The main issue is that this could cause the actions API to be initialized earlier than it previously was, which could lead to other unexpected behavior. For this reason, and especially for the sake of the event and entity APIs, which are currently only being loaded much later, I think that it would be better to wait and only hook these functions to these actions when these APIs are initialized. That way, the post types that are already registered will get handled as they do now, and any that are registered later will still be hooked up. And nothing will get registered twice.

**Closed** 2017-01-16 19:52 UTC
Labels: bug
